Individual exercise
Salisbury-University/cyber-security-backend pull request #23
Opened 2022-05-07 01:25 UTC by lamont1008

2022-05-07 03:40 UTC, JungAn2 requested changes
Couple changes with not using library and imports.
Also need to document functions

example
``` ts
/**
* returns given message
*
* @param {string} message
* @return {string} the message passed in
*/
 getMessage(message: string){
  return message;
}
```

2022-05-07 03:40 UTC, JungAn2 commented on app/routes/exercise.ts
> +import { ExericseService } from '../services/ExerciseService';
You don't use exercise service here. Delete this import

2022-05-07 03:40 UTC, JungAn2 commented on app/http/controllers/ExerciseController.ts
> +
Add documentation on what this does

2022-05-07 03:40 UTC, JungAn2 commented on package.json
> +    "front-matter": "^4.0.2",
We manually got front-matter so delete this library

2022-05-07 03:40 UTC, JungAn2 commented on tests/test-test.md
> +- bye
Delete this file since we are not using this

2022-05-07 03:40 UTC, JungAn2 commented on app/services/ExerciseService.ts
> +
Add documentation for the function also delete the extra line below the function

2022-05-07 03:40 UTC, JungAn2 commented on app/services/ExerciseService.ts
> +  getMetaData(Exercise_ID: string): Object {
Add documentation

2022-05-07 03:40 UTC, JungAn2 commented on app/services/ExerciseService.ts
> +  getDataType(s: string): any {
Add documentation

2022-05-07 03:40 UTC, JungAn2 commented on app/services/ExerciseService.ts
> +  getDisplay(exercise_ID: string) {
Add documentation

2022-05-08 02:05 UTC, JungAn2 approved these changes
Looks good

2022-05-08 21:45 UTC, wrathofrathma requested changes
Just a few requested changes. No logical changes, just some comments / naming things I think.

Also I'm not sure when we got into the habit of doing upper camel case snake case for arguments and constant upper case for some variables, but that'll likely be changed over the summer and enforced against next semester. 

Examples of what I mean for both

In several functions in the ExerciseService, we are passing the argument "Exercise_ID", which should be "exerciseID" if we go by google's typescript guide(lower camel case), or exercise_id, if we internally decide on snake case. 

In the AuthService, we define a few variables "PAYLOAD" and TOKEN_HEADER. Which should be in lower camel case or lower snake case(much like above, depending on what we decide). I'd say lower camel case is a good standard to go with. The only time we use constant upper case would be global constants / enums.

2022-05-08 21:45 UTC, wrathofrathma commented on app/http/controllers/ExerciseController.ts
> +    getInfo(req: Request, res: Response, next: NextFunction) {
The exercise controller's "getInfo" controller handles the login request?

2022-05-08 21:45 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +      return words[0] + words[2]
This is a pretty perfect area to get in the habit of commenting. At the moment I'm not sure why we're splitting by "<hr>", and in a year from now you might not remember exactly either. Nor what the contents of words[0] and words[2] are. 

Can you add some descriptive comments to shed light on those two things?

2022-05-08 21:45 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +      }
Comments on the goal of this for loop / what lexer[i+1] is.

2022-05-08 21:45 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +    }
This is okay for now if the tests are passing. 

In the future we should explore either a library to handle this heavy lifting. (All of these types are builtin, so I imagine there's something we can do)

2022-05-08 21:45 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +  }
Kind of a weird name for the function. The content of this is fine, but we're not really displaying anything. We're fetching / getting it. 

Refactor the name of the function / description to be something more accurate and it's good.

2022-05-10 13:32 UTC, wrathofrathma approved these changes
Good improvements on the commenting. 

Happy to see we're already fixing the casing of our variables as well!

Looks good to me.

2022-05-10 23:23 UTC, merged