Post request
Salisbury-University/cyber-security-backend pull request #27
Opened 2022-09-16 17:34 UTC by lamont1008

2022-09-17 02:18 UTC, JungAn2 requested changes
Change the commented stuff and also delete the cyber security backend folder during the next commit.

2022-09-17 02:18 UTC, JungAn2 commented on app/http/controllers/ExerciseController.ts
> +  getConst(req: Request, res: Response, next: NextFunction) {
Write documentation for this function

2022-09-17 02:18 UTC, JungAn2 commented on app/http/controllers/ExerciseController.ts
> +      const dat = ExerciseService.getStatus(
Change the constant name of dat. It is vague on what data it is actually holding

2022-09-17 02:18 UTC, JungAn2 commented on app/http/controllers/PreferenceController.ts
> +// import { Request, Response, NextFunction } from "express";
Don't know why you commented these but uncomment these

2022-09-17 02:18 UTC, JungAn2 commented on app/routes/exercise.ts
> +//import AuthMiddleware from '../http/middleware/AuthMiddleware';
Uncomment these

2022-09-17 02:18 UTC, JungAn2 commented on app/routes/preference.ts
> +//router.post("/", validate(preference), PreferenceController.post);
Uncomment

2022-09-17 02:18 UTC, JungAn2 commented on app/services/ExerciseService.ts
> +   * gets status of the problem
Instead of problem, try to use word exercise to be more consistent.
Also from here and down, create return type of each function.

2022-09-17 02:18 UTC, JungAn2 commented on tests/AuthController.spec.ts
> +// import { test } from '@japa/runner'
Uncomment theses

2022-09-17 02:18 UTC, JungAn2 commented on tests/AuthMiddleware.spec.ts
> +// import request from "supertest";
Uncomment

2022-09-17 02:18 UTC, JungAn2 commented on tests/AuthService.spec.ts
> +// import { test } from '@japa/runner';
Uncomment

2022-09-17 02:18 UTC, JungAn2 commented on tests/ExerciseController.spec.ts
> +// import { test } from '@japa/runner'
uncomment

2022-09-17 02:18 UTC, JungAn2 commented on tests/ExerciseController.spec.ts
> +//     test('/getInfo', async({expect}, done:Function)=>{
Write description of the test

2022-09-17 02:18 UTC, JungAn2 commented on tests/ExerciseController.spec.ts
> +//         test('/getInfo/Failed', async({expect}, done:Function)=>{
Write description of the test

2022-09-17 02:18 UTC, JungAn2 commented on tests/PreferenceController.spec.ts
> +// import request from "supertest";
uncomment

2022-09-17 02:18 UTC, JungAn2 commented on tests/PreferenceService.spec.ts
> +// import { test } from "@japa/runner";
uncomment

2022-09-22 01:23 UTC, JungAn2 approved these changes

2022-09-26 16:58 UTC, wrathofrathma approved these changes
Approved with minor changes

2022-09-26 16:58 UTC, wrathofrathma commented on app/http/controllers/ExerciseController.ts
> +  getConst(req: Request, res: Response, next: NextFunction) {
Get const isn't very descriptive 👀

2022-09-26 16:58 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +import { string } from "zod";
We most liekly don't want to be importing the data type from our input validation library.

This was probably an automatic import.

2022-09-26 16:58 UTC, wrathofrathma commented on app/services/ExerciseService.ts
> +  ): Promise<void | UnprocessableEntityException> {
This creates an entry in the database, doesn't _create the database_, right?

2022-09-28 16:38 UTC, merged