LogIn
Salisbury-University/cyber-security-backend pull request #34
Opened 2022-11-11 17:17 UTC by lamont1008

2022-11-11 19:11 UTC, JungAn2 requested changes
The code looks good but the comments and documentation does need to change.

2022-11-11 19:11 UTC, JungAn2 commented on app/http/controllers/AuthController.ts
> +      const tok = await AuthService.ldapJs(
instead of tok use the whole word token

2022-11-11 19:11 UTC, JungAn2 commented on app/services/AuthService.ts
> +   *
Add a description of what the function does

2022-11-11 19:11 UTC, JungAn2 commented on app/services/AuthService.ts
> +   * @param {String} token Authorization token attached to the HTTP header
param changes from token to uid

2022-11-11 19:11 UTC, JungAn2 commented on app/services/AuthService.ts
> +      // will create JWT token if user id is not found
The comment here is not correct. It doesn't create jwt token but creates a row inside the database

2022-11-11 19:11 UTC, JungAn2 commented on app/services/AuthService.ts
> +      "uid=" + uid + ",ou=users,dc=hslinux,dc=Salisbury,dc=edu",
Not sure about this one, but maybe putting the dn to the .env might be better way

2022-11-11 19:11 UTC, JungAn2 commented on app/services/AuthService.ts
> +          // return user
Not returning the user here so delete this comment

2022-11-28 16:01 UTC, wrathofrathma commented on app/http/controllers/AuthController.ts
> +      res.send(token);
So I think this is sending to the client, just the plain text token.

Do we want to send the token in a JSON object? Actually asking, up to you guys

2022-11-28 16:26 UTC, merged